### ISSUE TITLE
Support for API licensing and payment requirements

### ISSUE THREAD

**Issue by Snaver** [leeford/Backup-TeamsChat#11]
As of July 5, 2022, billing events for these protected Teams APIs will reach general availability and the communicated consumption rates will go into effect.

After completing the form I had to update the code to use [documented model parameter](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&tabs=http), see the change below to the _getAllMessages_ calls.

`getAllMessages?model=B`

https://devblogs.microsoft.com/microsoft365dev/upcoming-billing-changes-for-microsoft-graph-apis-for-teams-messages/

**Comment by leeford** [comment]
Good catch, I knew about this change but totally forgot to update this script for this. Did you want to do a PR with your modified code and take the credit? If not, I'll update it 🙂

Thinking about it, it makes more sense to add a switch for model **A** and **B** and if not provided run in eval mode.
