### ISSUE TITLE
Is there an issue running with PowerShell Core 7.2.5?

### ISSUE THREAD

**Issue by QuestNut** [leeford/Backup-TeamsChat#13]
Get-Chats: C:\Scripts\Backup-TeamsChat.ps1:589
Line |
 589 |      $userOutput += Get-Chats -userObject $userResponse -rootDirectory …
     |                                           ~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'userObject' because it is null.

**Comment by QuestNut** [comment]
Disregard, App registration set incorrectly. This error was thrown due to API permission "Type" set incorrectly on two of the permission names. Some of my API permission names were set to type of, "Delegated" and not "Application". Setting to type "Application" fixed above error.

**Comment by leeford** [comment]
Hiya - was about to come and say it works for me! (just tested it) :-)
