### ISSUE TITLE
Extend this awesome backup tool to channel conversations

### ISSUE THREAD

**Issue by Rowdy** [leeford/Backup-TeamsChat#8]
Is it possible to extend this awesome backup tool to channel conversations too?

**Comment by leeford** [comment]
@Rowdy This is something I could take a look at. Currently this is part of the https://github.com/leeford/Backup-Team tool, but that hasn't been updated it a while. Leave it with me!

**Comment by leeford** [comment]
Will put on hold whilst I work out if projects can be merged.
